version: '3.4'

volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:

services:

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "0.0.0.0:1883:1883"
    container_name: mosquitto
    hostname: mosquitto
    networks:
      - bde
    volumes:
      - "./conf:/mosquitto/config"

networks:
  bde:
    driver: "bridge"